'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,LocateFixed,RefreshCw,Droplets,Wind,Gauge,Eye,Sunrise,Sunset,CloudRain,MapPin,ArrowUpRight} from 'lucide-react';
import {Skeleton} from '@/components/ui/skeleton';
import {condition} from '@/lib/weather';
import {fetchWeather,searchCities} from '@/lib/weather-client';
type City={name:string;latitude:number;longitude:number;country?:string;admin1?:string};
export default function Home(){
 const [en,setEn]=useState(false),[city,setCity]=useState<City>({name:'Санкт-Петербург',latitude:59.9386,longitude:30.3141}),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<City[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[located,setLocated]=useState(false),[clock,setClock]=useState(Date.now());
 const seq=useRef(0),searchSeq=useRef(0),cityRef=useRef(city);const t=(ru:string,eng:string)=>en?eng:ru;
 async function load(c:City){const id=++seq.current;setLoading(true);setError('');try{const d=await fetchWeather(c.latitude,c.longitude);if(id!==seq.current)return;setData(d);setCity(c);cityRef.current=c;try{localStorage.setItem('weather-city',JSON.stringify(c))}catch{}}catch{if(id===seq.current)setError('weather')}finally{if(id===seq.current)setLoading(false)}}
 useEffect(()=>{let c=cityRef.current;try{const x=JSON.parse(localStorage.getItem('weather-city')||'null');if(x&&typeof x.name==='string'&&Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)&&Math.abs(x.latitude)<=90&&Math.abs(x.longitude)<=180)c=x}catch{}void load(c);
 const script=document.createElement('script');script.src='https://telegram.org/js/telegram-web-app.js';script.onload=()=>{const tg=(window as any).Telegram?.WebApp;tg?.ready();tg?.expand();if(tg?.initDataUnsafe?.user?.language_code)setEn(!tg.initDataUnsafe.user.language_code.startsWith('ru'));const theme=()=>{document.documentElement.dataset.theme=tg?.colorScheme||'light';if(tg?.themeParams?.button_color)document.documentElement.style.setProperty('--tg-accent',tg.themeParams.button_color)};theme();tg?.onEvent('themeChanged',theme)};document.head.appendChild(script);const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const id=++searchSeq.current;setResults([]);setSearchError('');if(query.trim().length<2){setSearching(false);return}setSearching(true);const ac=new AbortController();const timer=setTimeout(async()=>{try{const d=await searchCities(query,en?'en':'ru',ac.signal);if(id===searchSeq.current){setResults(d.results);if(!d.results.length)setSearchError('empty')}}catch{if(!ac.signal.aborted&&id===searchSeq.current)setSearchError('network')}finally{if(id===searchSeq.current)setSearching(false)}},350);return()=>{clearTimeout(timer);ac.abort()}},[query,en]);
 function location(){setLocated(true);setError('');const ok=(p:{latitude:number;longitude:number})=>{setLocated(false);void load({name:t('Моё местоположение','My location'),...p})};const bad=()=>{setLocated(false);setError('location')};const tg=(window as any).Telegram?.WebApp;const lm=tg?.initData?tg.LocationManager:null;if(lm){lm.init(()=>{if(lm.isLocationAvailable)lm.getLocation((p:any)=>p?ok(p):bad());else fallback()})}else fallback();function fallback(){if(!navigator.geolocation)return bad();navigator.geolocation.getCurrentPosition(p=>ok({latitude:p.coords.latitude,longitude:p.coords.longitude}),bad,{timeout:12000,maximumAge:300000})}}
 const c=data?.current,h=data?.hourly,d=data?.daily,w=condition(c?.weather_code??0,!!c?.is_day,en);const currentHour=c?.time?.slice(0,13);const ix=Math.max(0,h?.time?.findIndex((x:string)=>x.slice(0,13)===currentHour)??0);const n=(v:number|undefined|null,unit='')=>v==null?'—':Math.round(v)+unit;
 const localDate=data?new Intl.DateTimeFormat(en?'en-GB':'ru-RU',{timeZone:data.timezone,weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(clock):'';
 return <main className={`weather ${data?w.kind:'cloud'}`}><div className="shell"><header><a className="brand" href="/">weather<span>°</span></a><div className="top-actions"><button className="language" onClick={()=>setEn(!en)} aria-label="Change language">{en?'EN':'RU'}</button><button className="icon-button" onClick={()=>load(cityRef.current)} disabled={loading} aria-label={t('Обновить погоду','Refresh weather')}><RefreshCw size={20} className={loading?'spin':''}/></button></div></header>
 <div className="searchbox"><Search size={20}/><input aria-label={t('Поиск города','Search city')} placeholder={t('Поиск города','Search city')} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label={t('Очистить поиск','Clear search')}>×</button>}</div>
 {(searching||results.length>0||searchError)&&<div className="results" aria-live="polite">{searching&&<p>{t('Ищем город…','Searching…')}</p>}{searchError&&<p>{searchError==='empty'?t('Город не найден. Попробуйте другое название.','No cities found. Try another name.'):t('Поиск недоступен. Попробуйте ещё раз.','Search unavailable. Please try again.')}</p>}{results.map((x,i)=><button key={i} onClick={()=>{setQuery('');void load(x)}}><MapPin size={17}/><span>{x.name}<small>{[x.admin1,x.country].filter(Boolean).join(', ')}</small></span><ArrowUpRight size={17}/></button>)}</div>}
 <button className="locate" onClick={location} disabled={located}><LocateFixed size={16}/>{located?t('Определяем…','Locating…'):t('Использовать моё местоположение','Use my location')}</button>
 {error&&<div className="error" role="alert">{error==='location'?t('Не удалось определить местоположение. Разрешите доступ или найдите город выше.','Location unavailable. Allow access or search for a city above.'):t('Сервис погоды временно недоступен. Попробуйте обновить через минуту.','Weather service is temporarily unavailable. Please try again in a minute.')}<button onClick={()=>error==='location'?location():load(cityRef.current)}>{t('Повторить','Retry')}</button></div>}
 {!data&&loading?<div className="skeleton"><Skeleton className="h-8 w-52 mx-auto"/><Skeleton className="h-40 w-60 mx-auto"/><Skeleton className="h-44 w-full"/></div>:data&&<>
 <section className="hero" aria-busy={loading}><div className="eyebrow"><MapPin size={13}/>{t('ПОГОДА СЕЙЧАС','WEATHER NOW')}</div><h1>{city.name==='Санкт-Петербург'&&en?'Saint Petersburg':city.name}</h1><p className="date">{localDate}</p><div className="temperature"><span className="weather-icon" aria-hidden>{w.icon}</span><span>{n(c.temperature_2m)}<sup>°</sup></span></div><p className="condition">{w.label}</p><p className="feels">{t('Ощущается как','Feels like')} {n(c.apparent_temperature,'°')} <span>·</span> ↑ {n(d.temperature_2m_max[0],'°')} ↓ {n(d.temperature_2m_min[0],'°')}</p></section>
 <section className="glass hourly"><h2><span>{t('Ближайшие 24 часа','Next 24 hours')}</span><span className="section-note">{t('По часам','Hourly')}</span></h2><div className="hours">{h.time.slice(ix,ix+24).map((time:string,j:number)=>{const i=ix+j,cond=condition(h.weather_code[i],!!h.is_day[i],en);return <div className={'hour '+(!j?'active':'')} key={time}><span>{j===0?t('Сейчас','Now'):time.slice(11,16)}</span><span className="hour-icon" title={cond.label}>{cond.icon}</span><strong>{n(h.temperature_2m[i],'°')}</strong><small><Droplets size={11}/>{n(h.precipitation_probability[i],'%')}</small></div>})}</div></section>
 <div className="lower"><section className="glass week"><h2>{t('Прогноз на неделю','7-day forecast')}</h2>{d.time.map((day:string,i:number)=>{const cond=condition(d.weather_code[i],true,en);const min=d.temperature_2m_min[i],max=d.temperature_2m_max[i],low=Math.min(...d.temperature_2m_min),range=Math.max(...d.temperature_2m_max)-low||1;return <div className="day" key={day}><strong>{i===0?t('Сегодня','Today'):new Intl.DateTimeFormat(en?'en':'ru',{weekday:'short',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'))}</strong><div className="day-weather"><span title={cond.label} aria-label={cond.label}>{cond.icon}</span><small>{n(d.precipitation_probability_max[i],'%')}</small></div><span className="min">{n(min,'°')}</span><div className="range"><i style={{left:((min-low)/range*100)+'%',width:Math.max(5,(max-min)/range*100)+'%'}}/></div><strong>{n(max,'°')}</strong></div>})}</section>
 <section className="details" aria-label={t('Подробности','Details')}>{[
 [Droplets,t('Влажность','Humidity'),n(c.relative_humidity_2m,'%')],
 [Wind,t('Ветер','Wind'),n(c.wind_speed_10m)+' '+t('м/с','m/s')],
 [Gauge,t('Давление','Pressure'),n(c.surface_pressure*0.750062)+' '+t('мм рт. ст.','mmHg')],
 [CloudRain,t('Осадки сейчас','Precipitation now'),n(h.precipitation_probability[ix],'%')],
 [Eye,t('Видимость','Visibility'),h.visibility[ix]==null?'—':n(h.visibility[ix]/1000)+' '+t('км','km')],
 [Sunrise,t('Восход','Sunrise'),d.sunrise[0]?.slice(11,16)||'—'],
 [Sunset,t('Закат','Sunset'),d.sunset[0]?.slice(11,16)||'—']
 ].map(([Icon,label,value]:any,i)=><article className={'glass metric metric-'+i} key={label}><div><Icon size={17}/><span>{label}</span></div><strong>{value}</strong></article>)}</section></div>
 <p className="updated">{loading?t('Обновляем…','Updating…'):t('Данные на','Data at')+' '+c.time.slice(11,16)+' · '+data.timezone}</p></>}
 <footer><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">{t('Прогноз','Forecast')} Open-Meteo <ArrowUpRight size={12}/></a><span>{t('Время выбранного города','Times in selected city')}</span></footer></div></main>
}
