import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
function moduleAt(path,deps={}){const source=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const out={};new Function('exports','require',source)(out,n=>{if(!(n in deps))throw Error(n);return deps[n]});return out}
const calls=[];const s={WEBHOOK_SECRET:'test-secret',WEBAPP_URL:'https://example.com'};
const route=moduleAt('app/api/telegram/route.ts',{'@/lib/telegram':{secrets:()=>s,telegram:async(m,b)=>calls.push([m,b]),welcome:()=> 'Привет! 👋'}});
const req=(body,secret='test-secret')=>new Request('https://example.com/api/telegram',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':secret},body:JSON.stringify(body)});
assert.equal((await route.POST(req({},'bad'))).status,403);
assert.equal((await route.POST(req({message:{chat:{id:1,type:'group'},text:'/start'}}))).status,200);assert.equal(calls.length,0);
assert.equal((await route.POST(req({message:{chat:{id:1,type:'private'},text:'/start',from:{language_code:'ru'}}}))).status,200);
assert.equal(calls[0][0],'sendMessage');assert.equal(calls[0][1].reply_markup.inline_keyboard[0][0].web_app.url,s.WEBAPP_URL);assert.equal(calls[0][1].reply_markup.inline_keyboard[0][0].text,'🌤 Открыть погоду');
const weather=moduleAt('app/api/weather/route.ts',{'@/lib/weather':{upstream:async()=>({ok:true})}});
for(const q of ['','?lat=no&lon=0','?lat=91&lon=0','?lat=0&lon=181'])assert.equal((await weather.GET(new Request('https://example.com/'+q))).status,400);
assert.equal((await weather.GET(new Request('https://example.com/?lat=0&lon=0'))).status,200);
const search=moduleAt('app/api/search/route.ts',{'@/lib/weather':{upstream:async()=>({results:[{name:'Москва'}]})}});
assert.equal((await search.GET(new Request('https://example.com/?q=x'))).status,400);
assert.equal((await search.GET(new Request('https://example.com/?q=%3Cscript%3E'))).status,400);
assert.equal((await search.GET(new Request('https://example.com/?q=Moscow'))).status,200);
const failed=moduleAt('app/api/weather/route.ts',{'@/lib/weather':{upstream:async()=>{throw Error('network')}}});assert.equal((await failed.GET(new Request('https://example.com/?lat=0&lon=0'))).status,502);
console.log('PASS: webhook authentication, /start WebApp button, group exclusion, coordinate and city validation, upstream error handling.');
const w=moduleAt('lib/weather.ts');
const client=moduleAt('lib/weather-client.ts',{'./weather':w});
const realFetch=globalThis.fetch;const requested=[];
const forecast={current:{temperature_2m:14},hourly:{time:Array(24).fill('2026-09-25T12:00')},daily:{time:Array(7).fill('2026-09-25')}};
globalThis.fetch=async url=>{requested.push(url);return Response.json(forecast)};
assert.deepEqual(await client.fetchWeather(59.94,30.31),forecast);assert.match(requested[0],/^https:\/\/api.open-meteo.com\//);assert.equal(requested.length,1);
requested.length=0;globalThis.fetch=async url=>{requested.push(url);return url.startsWith('https:')?new Response('unavailable',{status:502}):Response.json(forecast)};
assert.deepEqual(await client.fetchWeather(59.94,30.31),forecast);assert.equal(requested.length,2);assert.match(requested[1],/^\/api\/weather/);
globalThis.fetch=async()=>Response.json({results:[{name:'Баку'}]});assert.equal((await client.searchCities('Баку','ru')).results[0].name,'Баку');
globalThis.fetch=async()=>new Response('unavailable',{status:502});await assert.rejects(()=>client.fetchWeather(59.94,30.31));
globalThis.fetch=realFetch;console.log('PASS: direct browser weather, server fallback, city search and both-provider failure.');
